# Form implementation generated from reading ui file 'app\forms\ui\create_shipment.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_CreateShipmentiWindow(object):
    def setupUi(self, CreateShipmentiWindow):
        CreateShipmentiWindow.setObjectName("CreateShipmentiWindow")
        CreateShipmentiWindow.resize(335, 134)
        self.centralwidget = QtWidgets.QWidget(parent=CreateShipmentiWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setMinimumSize(QtCore.QSize(30, 0))
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.data_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.data_label.setMinimumSize(QtCore.QSize(30, 0))
        self.data_label.setText("")
        self.data_label.setObjectName("data_label")
        self.horizontalLayout.addWidget(self.data_label)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.quantityBox = QtWidgets.QSpinBox(parent=self.centralwidget)
        self.quantityBox.setMinimumSize(QtCore.QSize(50, 0))
        self.quantityBox.setObjectName("quantityBox")
        self.horizontalLayout_3.addWidget(self.quantityBox)
        self.horizontalLayout_2.addLayout(self.horizontalLayout_3)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.itemBox = QtWidgets.QComboBox(parent=self.centralwidget)
        self.itemBox.setObjectName("itemBox")
        self.verticalLayout.addWidget(self.itemBox)
        self.supplaerBox = QtWidgets.QComboBox(parent=self.centralwidget)
        self.supplaerBox.setObjectName("supplaerBox")
        self.verticalLayout.addWidget(self.supplaerBox)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.create_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.create_btn.setObjectName("create_btn")
        self.horizontalLayout_6.addWidget(self.create_btn)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.cancel_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.cancel_btn.setObjectName("cancel_btn")
        self.horizontalLayout_6.addWidget(self.cancel_btn)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        CreateShipmentiWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(CreateShipmentiWindow)
        QtCore.QMetaObject.connectSlotsByName(CreateShipmentiWindow)

    def retranslateUi(self, CreateShipmentiWindow):
        _translate = QtCore.QCoreApplication.translate
        CreateShipmentiWindow.setWindowTitle(_translate("CreateShipmentiWindow", "MainWindow"))
        self.label.setText(_translate("CreateShipmentiWindow", "Дата:"))
        self.label_3.setText(_translate("CreateShipmentiWindow", "Количество:"))
        self.create_btn.setText(_translate("CreateShipmentiWindow", "Создать"))
        self.cancel_btn.setText(_translate("CreateShipmentiWindow", "Отмена"))
