# Form implementation generated from reading ui file 'app\forms\ui\main.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1031, 518)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.data_table = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.data_table.setObjectName("data_table")
        self.data_table.setColumnCount(0)
        self.data_table.setRowCount(0)
        self.data_table.horizontalHeader().setSortIndicatorShown(True)
        self.data_table.horizontalHeader().setStretchLastSection(True)
        self.horizontalLayout.addWidget(self.data_table)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.items_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.items_btn.setMinimumSize(QtCore.QSize(100, 0))
        self.items_btn.setObjectName("items_btn")
        self.verticalLayout.addWidget(self.items_btn)
        self.users_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.users_btn.setObjectName("users_btn")
        self.verticalLayout.addWidget(self.users_btn)
        self.orders_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.orders_btn.setObjectName("orders_btn")
        self.verticalLayout.addWidget(self.orders_btn)
        self.supplies_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.supplies_btn.setObjectName("supplies_btn")
        self.verticalLayout.addWidget(self.supplies_btn)
        self.suppliers_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.suppliers_btn.setObjectName("suppliers_btn")
        self.verticalLayout.addWidget(self.suppliers_btn)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.categoryes_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.categoryes_btn.setObjectName("categoryes_btn")
        self.verticalLayout_2.addWidget(self.categoryes_btn)
        self.create_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.create_btn.setFont(font)
        self.create_btn.setObjectName("create_btn")
        self.verticalLayout_2.addWidget(self.create_btn)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.items_btn.setText(_translate("MainWindow", "Товары"))
        self.users_btn.setText(_translate("MainWindow", "Пользователи"))
        self.orders_btn.setText(_translate("MainWindow", "Заказы"))
        self.supplies_btn.setText(_translate("MainWindow", "Поставки"))
        self.suppliers_btn.setText(_translate("MainWindow", "Поставщики"))
        self.categoryes_btn.setText(_translate("MainWindow", "Категории"))
        self.create_btn.setText(_translate("MainWindow", "+"))
